failure-threshold: warning

ignore:
  - DL3008
  - DL3009
  - DL3015
  - SC2086

override:
  error:
    - DL3001
    - DL3002
  warning:
    - DL3003
    - DL3004
  info:
    - DL3006

trusted-registries:
  - docker.io
  - gcr.io
  - ghcr.io
  - 012345678901.dkr.ecr.us-east-1.amazonaws.com

format: tty
no-fail: false
