default: true
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
MD033:
  allowed_elements:
    - br
    - details
    - summary
MD041: false
MD024:
  siblings_only: true
