rules = [
  RemoveUnused,
  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal,
  ProcedureSyntax
]

OrganizeImports.groupedImports = Merge
OrganizeImports.groups = [
  "re:javax?\\.",
  "scala.",
  "*",
  "YOUR_PROJECT_PACKAGE"
]
OrganizeImports.removeUnused = true

DisableSyntax.noVars = true
DisableSyntax.noThrows = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noXml = true

RemoveUnused.imports = true
RemoveUnused.privates = true
RemoveUnused.locals = true
RemoveUnused.patternvars = false
