version = "3.7.15"
runner.dialect = scala213

maxColumn = 100
indent.main = 2
indent.significant = 2

align.preset = more
align.tokens = [{code = "=>", owner = "Case"}, {code = "<-"}, {code = "->"}]

newlines.implicitParamListModifierPrefer = before

rewrite.rules = [SortImports, RedundantBraces, PreferCurlyFors]
rewrite.redundantBraces.stringInterpolation = true
rewrite.scala3.convertToNewSyntax = true

docstrings.style = SpaceAsterisk
docstrings.oneline = unfold
