version = "3.7.14"
runner.dialect = scala3

maxColumn = 120
indent.main = 2
indent.significant = 2

align.preset = more
align.tokens = [{code = "=>", owner = "Case"}, {code = "<-"}, {code = "->"}]

rewrite.rules = [SortImports, RedundantBraces, PreferCurlyFors]
rewrite.redundantBraces.stringInterpolation = true
rewrite.scala3.convertToNewSyntax = true

docstrings.style = SpaceAsterisk
docstrings.oneline = unfold

newlines.topLevelStatementBlankLines = [{ blanks = 1 }]
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
