image: Visual Studio 2022

build_script:
  - npm install
  - npm run build

test_script:
  - npm test

branches:
  only:
    - main
    - /release\/.*/

environment:
  NODE_ENV: test
  CI: true

artifacts:
  - path: dist\**\*
    name: build-output
