SECRET_KEY=your-secret-key-change-me
ALLOWED_HOSTS=archivebox.example.com
PUBLIC_INDEX=True
PUBLIC_SNAPSHOTS=True
PUBLIC_ADD_VIEW=False
ADMIN_USERNAME=admin
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=change-me-please
SAVE_TITLE=True
SAVE_FAVICON=True
SAVE_WGET=True
SAVE_WGET_REQUISITES=True
SAVE_SCREENSHOT=True
SAVE_PDF=True
SAVE_DOM=True
SAVE_SINGLEFILE=True
SAVE_READABILITY=True
SAVE_MERCURY=True
SAVE_GIT=False
SAVE_MEDIA=False
MEDIA_MAX_SIZE=750m
RESOLUTION=1440,2000
CHROME_BINARY=/usr/bin/google-chrome
CURL_BINARY=/usr/bin/curl
WGET_BINARY=/usr/bin/wget
