#! /bin/sh

# Monitors and workspaces
bspc monitor HDMI-1 -d 1 2 3 4 5
bspc monitor eDP-1 -d 6 7 8 9 10

# Window behavior
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config click_to_focus       button1
bspc config focus_follows_pointer true

# Padding (for polybar)
bspc config top_padding    32
bspc config bottom_padding 0

# Colors
bspc config normal_border_color   "#45475a"
bspc config active_border_color   "#89b4fa"
bspc config focused_border_color  "#cba6f7"
bspc config presel_feedback_color "#f38ba8"

# Rules
bspc rule -a Gimp state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a "Brave-browser:crx_*" desktop='^3'
bspc rule -a "jetbrains-idea" desktop='^4' follow=on
bspc rule -a "discord" desktop='^5' follow=on
bspc rule -a "Spotify" desktop='^5'

# Autostart
sxhkd &
picom --daemon &
polybar main &
nitrogen --restore &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &
dunst &
