load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "lib",
    srcs = ["lib.py"],
    deps = [
        "//common:utils",
        "@pip//requests",
    ],
)

py_binary(
    name = "server",
    srcs = ["server.py"],
    deps = [":lib"],
)

py_test(
    name = "lib_test",
    srcs = ["lib_test.py"],
    deps = [":lib"],
    size = "small",
)
