ServerName printing.example.com
Listen localhost:631
Listen /var/run/cups/cups.sock
LogLevel warn
MaxLogSize 0

<Location />
Order allow,deny
</Location>

<Location /admin>
AuthType Default
Require valid-user
</Location>

SSLPort 443
DefaultAuthType Basic
