gatling {
  core {
    # Base directory for all simulations
    simulationsFolder = user-files/simulations

    # Base directory for all resources (feeder files, bodies, ...)
    resourcesFolder = user-files/resources

    # Where results are written
    resultsFolder = results

    # Prefix used to build the base name of the output directory
    outputDirectoryBaseName = ""

    # Name to display in reports and console
    runDescription = ""

    # Encoding to use throughout Gatling for file and string manipulation
    encoding = "utf-8"

    # Whether the simulation should run without assertions
    mute = false

    # Whether to use class loader instead of compiler
    useOldJenkinsJUnitXmlFormat = false

    extract {
      regex {
        cacheMaxCapacity = 200
      }
      xpath {
        cacheMaxCapacity = 200
      }
      jsonPath {
        cacheMaxCapacity = 200
        preferJackson = false
      }
      css {
        engine = jodd
        cacheMaxCapacity = 200
      }
    }

    directory {
      simulations = user-files/simulations
      resources = user-files/resources
      results = results
    }
  }

  socket {
    connectTimeout = 10000
    tcpNoDelay = true
    soKeepAlive = false
    soLinger = -1
    clientReceiveBufferSize = 0
    clientSendBufferSize = 0
  }

  netty {
    useNativeTransport = true
    allocator = "pooled"
    maxThreadLocalCharBufferSize = 200000
  }

  http {
    fetchedCssCacheMaxCapacity = 200
    fetchedHtmlCacheMaxCapacity = 200
    perUserCacheMaxCapacity = 200
    warmUpUrl = "https://gatling.io"
    enableGA = false
    ssl {
      useOpenSsl = true
      useOpenSslFinalizers = false
      handshakeTimeout = 10000
      useSessionCache = true
      sessionCacheSize = 0
      sessionTimeout = 0
      enableSni = true
    }
    requestTimeout = 60000
    connectionTimeout = 6000
    maxConnectionsPerHost = 6
    perUserConnectionPoolSize = 100
    expireConnectionsAfterSeconds = -1
    ahcMaxConnectionsPerHost = 6
    ahcMaxRedirects = 5
    ahcMaxRetry = 2
  }

  data {
    writers = [console, file]
    console {
      light = false
      writePeriod = 5
    }
    file {
      bufferSize = 8192
    }
    leak {
      noActivityTimeout = 30
    }
    graphite {
      light = false
      host = "localhost"
      port = 2003
      protocol = "tcp"
      rootPathPrefix = "gatling"
      bufferSize = 8192
      writePeriod = 1
    }
  }
}
