source "https://rubygems.org"
ruby "3.2.2"

gem "rails", "~> 7.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.0"
gem "devise", "~> 4.9"
gem "pundit", "~> 2.3"
gem "image_processing", "~> 1.12"
gem "aws-sdk-s3", "~> 1.136"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
  gem "pry-byebug", "~> 3.10"
end

group :development do
  gem "web-console"
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "shoulda-matchers", "~> 5.3"
  gem "simplecov", require: false
end

gem "bootsnap", require: false

platforms :jruby do
  gem "activerecord-jdbc-adapter"
end
