# Gemfile for a small Rails-ish service
source 'https://rubygems.org'

ruby '3.3.0'

gem 'rails', '~> 7.1.0'
gem 'puma', '>= 6.0'
gem 'pg'
gem 'redis', '~> 5.0'

group :development, :test do
  gem 'rspec-rails', '~> 6.1'
  gem 'rubocop', require: false
end

group :production do
  gem 'lograge'
end
