[global]
history_size=28800
refresh=2

[outputs]
; csv_file_name=/tmp/glances.csv
; html_output_path=/tmp/glances.html

[webserver]
host=0.0.0.0
port=61208
open_browser=False
time_between_saving=60

[thresholds]
cpu_careful=50
cpu_warning=70
cpu_critical=90
mem_careful=50
mem_warning=70
mem_critical=90

[cpu]
disable=False
refresh=2

[mem]
disable=False

[diskio]
disable=False

[network]
disable=False
hide=lo

[processlist]
disable=False
