span_storage_type: elasticsearch

query:
  port: 16686
  base-path: /jaeger

collector:
  num-workers: 50
  queue-size: 2000
  zipkin:
    host-port: ":9411"
  http-port: 14268
  grpc-port: 14250

agent:
  reporter:
    type: grpc
    grpc:
      host-port: "jaeger-collector:14250"

storage:
  elasticsearch:
    server-urls: http://elasticsearch:9200
    index-prefix: jaeger
    num-shards: 5
    num-replicas: 1

sampling:
  strategies-file: /etc/jaeger/sampling_strategies.json
