[libdefaults]
    default_realm = EXAMPLE.COM
    dns_lookup_realm = false
    dns_lookup_kdc = true
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
    default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
    permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96
    no_addresses = true

[realms]
    EXAMPLE.COM = {
        kdc = kerberos1.example.com:88
        kdc = kerberos2.example.com:88
        admin_server = kerberos1.example.com
        master_kdc = kerberos1.example.com
        default_domain = example.com
    }
    CORP.EXAMPLE.COM = {
        kdc = corp-kdc.corp.example.com
        admin_server = corp-kdc.corp.example.com
    }

[domain_realm]
    .example.com = EXAMPLE.COM
    example.com = EXAMPLE.COM
    .corp.example.com = CORP.EXAMPLE.COM
    corp.example.com = CORP.EXAMPLE.COM

[capaths]
    EXAMPLE.COM = {
        CORP.EXAMPLE.COM = .
    }

[logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log
