# /etc/security/limits.conf
# domain        type    item            value
*               soft    nofile          65536
*               hard    nofile          65536
@developers     soft    nproc           4096
root            hard    memlock         unlimited
