# MPD configuration
music_directory		"~/Music"
playlist_directory	"~/.local/share/mpd/playlists"
db_file			"~/.local/share/mpd/mpd.db"
log_file		"~/.local/share/mpd/mpd.log"
pid_file		"~/.local/share/mpd/mpd.pid"
state_file		"~/.local/share/mpd/mpdstate"
sticker_database	"~/.local/share/mpd/sticker.sql"

bind_to_address		"127.0.0.1"
port			"6600"

log_level		"default"
restore_paused		"yes"
auto_update		"yes"

replaygain		"album"
volume_normalization	"no"
crossfade		5

audio_output {
    type		"pipewire"
    name		"PipeWire Sound Server"
}

audio_output {
    type		"pulse"
    name		"PulseAudio"
    server		"127.0.0.1"
}

audio_output {
    type		"httpd"
    name		"HTTP Stream"
    host		"0.0.0.0"
    port		"8000"
    encoder		"lame"
    max_clients		"0"
    quality		"5.0"
    bitrate		"128"
    format		"44100:16:1"
}
