# ncmpcpp configuration
mpd_host = localhost
mpd_port = 6600
mpd_connection_timeout = 5
mpd_music_dir = ~/Music

ncmpcpp_directory = ~/.config/ncmpcpp
lyrics_directory = ~/.local/share/lyrics
store_lyrics_in_song_dir = no

colors_enabled = yes
empty_tag_marker = <empty>

song_list_format = {$4%a - }{%t}|{$8%f}$R{$3(%l)}
song_status_format = $b{{$8"%t"{ by $3%a{ from $7%b{ (%y)}}}}|{$8%f}}$R{$3%l}
song_library_format = {%n - }{%t}|{%f}
alternative_header_first_line_format = $b$1$aqqu$/a$9 {%t}|{%f} $1$atqq$/a$9$/b
alternative_header_second_line_format = {{$4$b%a$/b$9}{ - $7%b$9}{ ($4%y$9)}}|{%D}

playlist_show_remaining_time = yes
clock_display_seconds = no
display_volume_level = yes
display_bitrate = yes

media_library_primary_tag = album_artist
media_library_albums_split_by_date = yes

visualizer_data_source = /tmp/mpd.fifo
visualizer_output_name = Visualizer
visualizer_in_stereo = yes
visualizer_type = spectrum
visualizer_look = ●▋
visualizer_color = blue, cyan, green, yellow, magenta

startup_screen = playlist
user_interface = alternative
