passwd:     files systemd
group:      files systemd
shadow:     files
hosts:      files myhostname resolve [!UNAVAIL=return] dns mdns4_minimal
networks:   files
services:   files
protocols:  db files
resolv:     dns
