platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

target 'MyApp' do
  pod 'Firebase/Analytics', '~> 10.21'
  pod 'Firebase/Crashlytics', '~> 10.21'
  pod 'Alamofire', '~> 5.8'
  pod 'SDWebImage', '~> 5.18'
  pod 'KeychainAccess', '~> 4.2'
  pod 'SnapKit', '~> 5.7'
  pod 'lottie-ios', '~> 4.4'

  target 'MyAppTests' do
    inherit! :search_paths
    pod 'Quick', '~> 7.0'
    pod 'Nimble', '~> 12.0'
  end

  target 'MyAppUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.9'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
