myhostname = mail.example.test
mydomain = example.test
myorigin = $mydomain
inet_interfaces = all
inet_protocols = ipv4
mydestination = $myhostname, localhost.$mydomain, localhost
mynetworks = 127.0.0.0/8, 10.20.0.0/16
relayhost = [smtp-relay.example.test]:587
smtpd_tls_security_level = may
smtpd_tls_cert_file = /etc/ssl/certs/mail.pem
smtpd_tls_key_file = /etc/ssl/private/mail.key
smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination
