# A list of devices you want to take the screenshots from
devices([
  "iPhone 15 Pro",
  "iPhone 15",
  "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US",
  "de-DE",
  "fr-FR"
])

# The name of the scheme which contains the UI Tests
scheme("MyAppUITests")

# Where should the screenshots be stored?
output_directory("./screenshots")

clear_previous_screenshots(true)

override_status_bar(true)
