# Stirling-PDF Settings
# https://github.com/Stirling-Tools/Stirling-PDF

security:
  enableLogin: true
  initialUsername: admin
  initialPassword: changeme_on_first_login
  csrfDisabled: false

ui:
  appName: Stirling-PDF
  homeDescription: Self-hosted PDF manipulation tools
  appNavbarName: Stirling-PDF

system:
  defaultLocale: en-US
  googlevisibility: false
  customStaticFilePath:
  maxFileSize: 100

premium:
  enabled: false
  key:

metrics:
  enabled: true
