[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujkf03M=
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = z0oAF4e/PYbRGzFEMRmHFtV1NVWHMVNMHlG7z8C1fkU=
Endpoint = vpn.example.com:51820
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
