# WSL configuration for this distribution

[automount]
enabled = true
root = /mnt
options = "metadata,umask=22,fmask=11"
mountFsTab = true
crossDistro = true

[network]
generateHosts = true
generateResolvConf = true
hostname = my-wsl-machine

[interop]
enabled = true
appendWindowsPath = true

[boot]
systemd = true
command = service docker start
